### PR TITLE
Add diff colors for Sourcegraph, change for Solarized (light)

### PR DESCRIPTION
**Pull request by attfarhan**
Updates diff colors for the Sourcegraph theme and changes them for Solarized (light) so that they fit with the colors we'd like for diffs on Sourcegraph. 

Note: I copied over the Solarized (light) theme file into the Sourcegraph directory.

### CODE REVIEW

**Comment by emidoots** [comment]
You will have to rename solarized light to something else or else the two will conflict

Is there a way to see your changes to solarized light? Maybe you can commit the initial file first, then commit your changes on top?

**Comment by attfarhan** [comment]
@slimsag updated. See https://github.com/slimsag/syntect/pull/5/commits/f2bba5efbc5551a0a5ac8517a240458c1cf28ff3 for the changes to solarized light.

**Comment by emidoots** [comment]
Asks:

- Rename `Sourcegraph Solarized (light).tmTheme` -> `Sourcegraph (light).tmTheme` (we will only ever have one light theme most likely).
- There is a key at the top of the file you also need to update: https://github.com/slimsag/syntect/blob/f2bba5efbc5551a0a5ac8517a240458c1cf28ff3/testdata/Sourcegraph/Sourcegraph%20Solarized%20(light).tmTheme#L6

**Review by emidoots — APPROVED** [review]
Looks good!

**Comment by emidoots** [comment]
Thanks!

**Pull request merged**
